spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banque?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL

  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
  host: smtp.gmail.com
  port: 587
  username: volta1528@gmail.com
  password: Volt@2024#
  protocol: smtp
  tls: true
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          ssl:
            trust: smtp.gmail.com

server:
  port: 8090
