server:
  port: 8092

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/hotel
    username: hotel
    password: hotel@@
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    # database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: volta1528@gmail.com
    password: Volt@2024#
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            ssl:
              trust: smtp.gmail.com
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
